---
title: "About"
---

My research focuses on the interplay between learning and memory, and I am specifically interested in the "bright side of forgetting". At both the individual and collective levels, forgetting processes shape the ways that we integrate information from our environment. Increasing our knowledge of these phenomena helps us to better understand how we learn and remember relevant information, which is key to academic success. With this information, we can improve students' memory of course content and help them become better learners.

Outside of the lab, Chris enjoys knitting and playing tennis. You can also find him playing around with computer code, listening to podcasts, or devouring a good book.

## Education

**University of Minnesota - Twin Cities**, [Ed Psych](https://edpsych.umn.edu/) \| Minneapolis, MN

Ph.D. Student in Educational Psychology\| 2022 - Present

**University of Minnesota - Twin Cities**, [Cog Sci](http://www.cogsciphd.umn.edu/index.shtml) \| Minneapolis, MN

Ph.D. Student in Cognitive Science\| 2020 - 2022

**University of Minnesota - Twin Cities**, [MBS](https://ccaps.umn.edu/biological-sciences-masters-degree) \| Minneapolis, MN

Master of Biological Sciences in Anatomy Education \| 2016 - 2020

## Lab Affiliations

[Keisha Varma Research Lab](https://edpsych.umn.edu/research/labs/keisha-varma) \| Graduate Student Researcher \| University of Minnesota - Twin Cities

[Feedback Lab](https://edpsych.umn.edu/research/labs/martin-vanboekel) \| Graduate Student Researcher \| University of Minnesota - Twin Cities

[Learning Informatics Lab](https://innovation.umn.edu/informatics/) \| Graduate Student Researcher \| University of Minnesota - Twin Cities
